MODEL:
  WEIGHTS: detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
  MASK_ON: false
  ROI_HEADS:
    # maskrcnn_unified.py overwrites NUM_CLASSES from the orth COCO train JSON.
    NUM_CLASSES: 1
    BATCH_SIZE_PER_IMAGE: 512
    SCORE_THRESH_TEST: 0.05
  ANCHOR_GENERATOR:
    SIZES:
    - - 16
      - 32
      - 64
      - 128
      - 256

INPUT:
  MIN_SIZE_TRAIN:
  - 640
  - 800
  - 1024
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

DATALOADER:
  NUM_WORKERS: 4
  FILTER_EMPTY_ANNOTATIONS: false
  SAMPLER_TRAIN: RepeatFactorTrainingSampler
  REPEAT_THRESHOLD: 0.05
  KEEP_NEGATIVE_RATIO: 0.2

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  MAX_ITER: 12000
  STEPS:
  - 8000
  - 11000
  GAMMA: 0.1
  WARMUP_ITERS: 500

TEST:
  EVAL_PERIOD: 200

OUTPUT_DIR: output/maskrcnn_orth
