_BASE_: coco/instance-segmentation/Base-COCO-InstanceSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "MaskDINO"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    # maskdino_unify.py overwrites NUM_CLASSES from datasets_coco/datasets_to_coco.py.
    NUM_CLASSES: 1
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 1024
    NUM_FEATURE_LEVELS: 3
    TOTAL_NUM_FEATURE_LEVELS: 3
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MaskDINO:
    TRANSFORMER_DECODER_NAME: "MaskDINODecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 1.0
    CLASS_WEIGHT: 4.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    BOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 50
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    INITIAL_PRED: True
    TWO_STAGE: True
    DN: "seg"
    DN_NUM: 100
    INITIALIZE_BOX_TYPE: "bitmask"
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.5

INPUT:
  MIN_SIZE_TRAIN:
  - 300
  - 400
  - 500
  MAX_SIZE_TRAIN: 600
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 600
  MASK_FORMAT: polygon

DATALOADER:
  NUM_WORKERS: 4
  FILTER_EMPTY_ANNOTATIONS: false
  SAMPLER_TRAIN: RepeatFactorTrainingSampler
  REPEAT_THRESHOLD: 0.05
  KEEP_NEGATIVE_RATIO: 0.1

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 3000
  STEPS: []

TEST:
  EVAL_PERIOD: 1000

# Training logger: "tensorboard" or "wandb".
LOGGER: wandb
WANDB:
  PROJECT: maskdino
  ENTITY: "intraoral"
  NAME: "maskdino_caries"

OUTPUT_DIR: output/maskdino_caries